name: Deploy Static Site to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust to your primary branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        run: |
          # Create or switch to gh-pages branch
          git checkout -B gh-pages

          # Copy all files from the source branch (main or master) to this branch
          git add -f .
          git commit -m "Deploy to GitHub Pages"

          # Force push to gh-pages branch
          git push -f origin gh-pages

          # Return to main branch
          git checkout main